language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jet090892/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jet090892/docker-react npm run test
